baseURL = "dean.thesimplekid.com"
languageCode = "en-us"
title = "The Dean Lab"

enableGitInfo = true

[params]
    cloudinary_id="codegaucho"
    email = "cory.dean@gmail.com"
    google_scholar = "z3z-PV8AAAAJ&hl"
    copyright = "Â© The Dean Lab 2021"